# Generated by Django 5.1.4 on 2025-01-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_alojamiento', models.CharField(choices=[('Tienda', 'Tienda'), ('Cabaña', 'Cabaña'), ('Caravana', 'Caravana')], max_length=20)),
                ('numero_personas', models.PositiveIntegerField()),
                ('estado_reserva', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campista.campista')),
            ],
        ),
    ]
